version: build-{build}
configuration: Release

environment:
  matrix:
  - job_name: macOS Mojave
    appveyor_build_worker_image: macos-mojave
    INSTALL_DIR: sfizz-$(APPVEYOR_REPO_TAG_NAME)-macos

  - job_name: Windows x86
    appveyor_build_worker_image: Visual Studio 2019
    platform: x86
    VCPKG_TRIPLET: x86-windows-static
    PATH: C:\Program Files (x86)\Inno Setup 6;%PATH%

  - job_name: Windows x64
    appveyor_build_worker_image: Visual Studio 2019
    platform: x64
    VCPKG_TRIPLET: x64-windows-static
    PATH: C:\Program Files (x86)\Inno Setup 6;%PATH%

  # Made with https://github.com/sfztools/code-signing
  CODESIGN_IDENTITY: codesign.sfz.tools
  CODESIGN_P12:
    secure: +4U0JnWGrDdpvpi1UMH/XKuaoej/UWKL5ae1DEATCSOLDJGjeiFNvCDWx4Ej8PQ+0uAyxxhLTwEozqdxP0c+LRN4cHddZPm7w9IxWGIYAnjgPiukZNcFHTg7YMk6LZ+iweSVzc4WiompMYNSInTVTOYw1tosgSWBaYPM1BpphErzU8yLp499bCpf0Zgeqf3HZWmUfVn71gIbaQyMaLunyefX2kYisAsJt0qga3uyJB+Ww+J/cWPHSDuP+O8zRqQFwxmMkr/jkA9bF0rHYy2hIe+/6owLDYMQObcGgacHXeGIaFxBPgBYvifA31t5xpMfNhc58X56eqzKTanxtu8tv9r/LobYNk4h9OSDtjsSWqJl72eY1RQXnjQApzE0rfHPxbvxdQ6c9yq0kWhK9TtmaU1fAowNBy3g7yJ5JH5GTGI1CHiCoijbANMyn5p4zNdqBHg1DRQn1IE6QODj8x6JnuXU2C9rvhAMIUyczrG9AvEldxa3IAX2pd+c6o2hGpWJavN875FSQqBHd7rILzOc9hqLfpAxd/MAvzB+DKYgHWanObXJKQf5b8U5XVSdgNePECYoEokEX/9RMQNLd/ZL/1n6qfoQq2EWLpbpoKd2ohCHmw6Qf9GI74kzaH/dk8mfGVYPTE8s07niX2Byb2QDVmaUNW4VvrTHxnBIOqCVmq1FoAoOqC8PBY2VbmKU3RK6QsO3jpa3OBKb6kiE/Xfjg/3cfutKdvFdbK9Xkd6nFBc4F53xEURmlAE++8pY6LSAZMpCQpgGb4obTn6UPX2NrZ4EedI18637ilxK4xPsNxEV/wBPzP/s05ydFoJuaYbOUy0PHNvgVos3VLMMdmsVa8PBbKxfc8ZHNxZrfoHQwdmjdQwbi6x4/hgSFHYrDLCVP/zlSmGal8oOeEdqVlZkCbo1odZT4OWy3MByx3gHsWAPMiERmUxzsXMyMaBtRSy1F+SB3sbfhjn07gLgI+QkchcWitq66uGxf9OleoOVyOipyccFInk6Ss3xOIRXvSD64Xa6nOvOx1hfq3FzYEojvRqMjye0eOc9ivXLAb1BGh9JySc4idFmQKi7TQKybshEVe2kXg2G5rRiYQqMp7dQXmLHGiv0o0aOMfAIl1v8RjY1Z6sgmffOnv0VVCU7tFI19HQj0tG84Xf5aVniBlAyE2cOQHgYKV1u1xFdmW0jsbtoSzo8UpPHjNsS5jL7Ess9fUPB3kBwPogmwjiHEzSG91w3OHMpEMFkhZ+WqS1g5Wfc3LbPUfVyCCA1sgnHHHWoKr3I/2puhNfwFJ2G3zWOjxZrep6x1WThMpjhEAkeq0NS+2zJKtWhhvFLmAKbotZMAFWbUAbhf5o8Q1NAvrZ4KJ6QGJCo6YqV9r5MyQi0y08MPtUrjR56/YmOSfDCTXXPdbLwWuSRF/TlkIlVuuEkfSO1QdcFUx4uHX/uBi9cOtzJvDbC2a0TqdVcxFRpSG7DzSFf8x3ng8l63TdvsqSFpGnRj6TfRQfJBdd5AXKIWG6emf4TwilePcEF3Wh12A4r55Flc0MkjD/zC/wfQaJaCqUniUJKYK/dT6u/5sZ63+13NTwjOLjVb7Mw7AUCgZ5S1D152FzvR9K7UEmv11bsX4kJnykUKL+gRqwxZYWNCiYgskkpNfLT7wJ7kGMoZ5qbxAHoN/J4V/E8VE3FQtwvoGk5bQL/QH2dFhHqYp/ty6lfiKJcew3nO691yMSCmM/ix5g7uvl8Lw7nf25qCt5Qf6GbtEX2LthosWlV78T15r960IVb3uv948SIhgIWjKNfeBuD6gIDYbmvAb4mdW+gzH1df/+QwaL7hl9u7G8pLr+xqRY1VyXyOaIY05UtJQYvvC0HBFNtd8q+xKw+1fjAlX5yNbcseBKBBLxHB5UVzsXv7T7kkdoH73O9UVbar61r5SNgYLJnE5yBrkqgWoKtFwc+tQQ4suxq0pZlKKzNMyNkR1hPy9tvQ5XvvUBTcXazR4JhW76YZXbPmDsQTi/0fMAxcMwKdoEfk2cKB2V9MCEgyMmkP7LFFqxq/rvlxroSa20BKv9KY65TlFMm6Ei6eD4f5x1dkQwEkcAOiz5hxlR9pT86uVA/O4og9xbF0YYzpF/fxvzcFbGeWPG5SOZYPOc6xSwADFtglyhaInDKqPjZ1MploJvQspryNtZ2zmQ5S4Mteyjgai9HncV8dFWp1NUQBK1YbLZaIVmMvnSh//yTk6CPxzjgSxAcpG/ofL0aWIqaQN1iugKtt5I65h0TSL3poJY5jZMX5WXKDI4SLM+/R6yqMkLg0D0zzL2/ITArMnWmBmA5Cb9Rvyz7Sd6hVkCzM2sAR8g4KR+q4IizbMoQuaUnuUBB+PBOdXqJLVXM1j5577V3uk6Kdvx433z+jFf5HFq1s4JGZot7zKXbNNbRZnBIkdQdhQIwoyWaClnYnBQETBAbh0Sxiq2fdk5PIw/NatXOJHw6jYJlonB2GsgxZfIIrf2HQ5MuBsJNy7VNC3Hf376xsdTRwYCADId6atd8NxNcRXKCqiZm9JRL38nOEntwhX6rskJlSzx2R5pKB8wYZvAzECBWNgc19Um6W7Qd7ydl5anv9D9/pX2lnxjKZloKN5ghvurLoR8KcQPIuqcAkb+nDsG7dv8f30TLzgOHPiUjiXjlIWyVu8UabTpGnoGK5mtOttXpf/lptOIPwuyi0Z+0ic9nstRD7cJSnm6pnnln+oEgPU2ntEFTcPT44m1vq5lct9gpOA2DxrF4JJnPMsYbDEEwZWQAW/eOttzaS8Leebnywd6N5ROAj8VopBLxty/FJrmQt/6mTFIupfd/WP5qD7fdgttg8PIQgOrWvTAIL2xu9v5efWO5wvcSRxG45t9wNFpzAav5hpOka0ksekTdfRKum/fx2OrqZtH2uQKxoXM5+EtD+GEDqUNQs90EAX7h5h6tZ7/rntR0MSM0EWsicYKDIaE2Ax78DmTIkch9swPtVO/CcHrUrvvXX1DuDI2n+/ceuyTfYzlcGlowx8R9nrngn6CmQYmPp9LYGy0KpMpbCmEaUI+A8MgBAFj9bxnTaK8bYZRMBdfgZih2Yn4NPf1WV4lPbUXzig1NgvITMtRpcCxBljitVgjK0Ov2AC32mR+1cWkb52Mvg0hED0AS/hy/lWRxZXkLeF6Cwh1U4OQaKmFOjv8wT7g2+ldn1OuCdUSg99bMiz3vwI1d5+XAwVpi/cBzQpE3rOozH/Yjc4RCzO6wxSla/yV2QcwdVzJAxUeeK7TMn/XGl4h9MUciauwFbVHDTMMO3mE+qC5TTe/1lEaLjyVyUZ+zbdN/upGVeOi0QTT9o2QqDDuSV6WmDS+8t1mYqckrXN570f9fAkaveKaC8CxkM1HE+BcgjprSbopsf4YJbSjeIBkdv9pVtmFOkGeSiBdnAI+w6Qf0C+pyschb48935zDsOVgEdzuqA5JKnU2UyVOWlzLMOF2s/ZaMZaUpjZ5C8Xt8Pc3wV5LxYUICDrBdoC8Ej0oyq7YjmT9NU4Xuq8thmJIccijNocKPp2bf1uu3/moD7FNVoncbUvesycM/05tRKNtctSm66T48EKWZkEnlJDi4m9ZZKNy9MGH5G4Kd23lQoif3opFtkWEXEeUbllgv36sXtnzoM611KOh+Fr4eDZ+aXkz9S6aB/gskzxb7VgKCcs/ovyfnYIL8BGRW9mXshmauNSFDLN5Y6IvZ8hqGqxKqRMvTfizA5z8HDeEweEr5LFsNKdLS3wczlPk/OxuDMu2Glm7FPrzRy7I3uWqg8yp/09Um93IqPn1dkoPLli3+QWen38DsHAH1C18s7SqxwE2Co32IlotvPgM5+Mfi7XIfAR2qKNbwqs8OuNzKHo7vgP5swFJOImVoGRiNnw+tPHBTtzNMtL53ZerSd8sni9P+3/pXXiDlyWUSEiPuO+2AEXOtUwr4wJ8qj24+j4NzRbX96jzI2llrm4TRJEMalEZ0UDhe6x7cq00ilycZc2zfEUiBxj8CXN/ZZvWLLuELzNaxT8eZsWRUD/7h/2F/r9e3uC0rch3eShfIARhOZ81dXWKTfnFoZlvl8cN7HntFD6nKfr7LW1J/CYSFcg6mUAQlyOWof474W4ZwvXyEwfwIVZvHsksX2yp9xzhtcWp4cQPcI5N2AzHydwGyKXtusAElfnBldLOXyCNxVp/DIw3gzoLU3OKGy2xlKeSvvomlA5pTrQ+AM4tHINl20GUa1b2QRWCJ2xUP0725lekZVG8/rDwAxZo7VzFI4U7713qXzYavungOUL8c3s/TCKBF1tz9U8xo8c3K4wnSptOrCeoda/V2A2169V47IL0EqCb48SPitkX1/87o0Q6AYJiF
  CODESIGN_PASSWORD:
    secure: 2AP8Z/4YZ+5f8BCxbS2YzwAXhDpXwsWzxy99eSmdyYthValcy+tT4898cVPSOUAe/vzcR6wL2qyCT/eFKXT+rDiDhooBJUL7FXOJ802j4X0=
  SFZTOOLS_CRT:
    secure: NE+JydaGOvF5jtPtL2iv4ET/V2UQFyLWUl9JWgtHl/L0QI70bhv0VWkHr/G2vIgD4I83JlKHrdR8WIs9aYVFQCZnyn2Mm5vxjwDJ8yKiqVS+pSqYJmS0VHn+ey48bOooBuT9pG53qBge+PAwkQkF8kC/JY76AvPL1LakYOTFL9rFuFnrRpSydB3r6Uco1PeWHpjSbCEn5j8YEN7afRAEEbrz3X/WJpyqnPrbuqv/8T81Zc14ib87u48BsQ2f8kz2hCeMgOdB62CxApSmVlF1T4wNq532IH6GpZJL5Um7qEvz4q86KuA64HBURHieLZZxx52nnvogC/9Z5D5VF6GIHhEsA8GnLd4S1KLFcrkhhB/GBJ1njDR0alrca1k7BXj9DrGpVwtCzMjiZFEdpWOFAhaiH1yeMdwtgzYPgCiG7RZ6gPzXKh6OXM7qnPasKy3dbCuDr3doF52xg0I8il64hLgDKiZp0a1fk4JTt2gSI7xpCLmX7Egp/wp8vxYbCDhHVjnPcshw673AOjqsIOwVghxoUUnXohuBVkZHvB/2t0nNJkhmCWVO2qaVuA+uR1uu6aIiTIbM151ZsuwAy97AEuN28H9qrI7bgzcN95LkcIgPfeyvCYWPEL3605zSeDjYT12gEw8KgC3oKej1CTk/AFtCwjN80RoUnYgGt3Zwo8BDyduEBNRXKQ7BGp4PV/BuIHv8LHBcWdqu3zrLB6iaart0q2Fcxt149TOpYBthOdumL3yxh8Na7JHA1ffS/MympAG7RMzAxWY/Zvd331nzXPkrF4wmRrJOYZsoTvL77N78IaeWixD08gCgXr8hoO9S0udFRKS6TK9KTDavkYaA2kS5YJU51kLNce2KBklJ8CcpwUu5OvIZrMFMzbtL53Mo+I3+axYq7bExUa2It283PoCnBHKHeXg1aLMMXWjrC9Lv82hTlAh1ESU88wSNpnhv4eztB9KrzSdo/veJy9oWK9vKH1bVSwJOs0XmIyiKULPm7NFywC+8Jl+Vg0F5FGY+rhxDL8hX0geXRPNiPPX8tTXT/jRmVMQE+MT/9Ixq3fkiQPkBfECov0OvPOYJSXRM9PG+z22QrBaGpo83LJj1f0WvqR6y8B1y2YZNBvYr/YG7QZMOuggGxyO9tYL/szV6vVYtfz3PFIpkCEisDl/JJLniXoBkQrFIA6piQ3tICBLIiPGAj+SD7ma8U36jR5Lkbt+9gHGvyDvJN1qeSTzrnB2LM7IQJF6jyIVLGzbPNLMtVOfoeQNpd1cDq/ARPVjZNIRewVRPNQBA4uVlI9MAHNzULC+/eUgJi5IBowk1+DfoQhXSd9fVDBefshfqNTlEJr3KwidymPa8vh4JmneeAe3ydQ+br18MEHn4lIFbTe7/9skznloTIFRFc9NbwEdTLd+uIkZ1Zppcn+r9KmoZo0EQ0eZhXb5PaD4zCheeONCy/DQesk2VSI3SRY/dCRQoz2mtzcUt08mVsC1TcJOyNZ+UamwCvcYB/GhhI2HFNHL+6SNupBMa3M9WFsq/fRZdoI9WV9JfWVJAcIfCYI4K3hVWBEQKHVRFzJ35GJhSLD2JCYBKFaxBN5kaJw9MASixyCOmh3EwCy42qGdE3QREbfCXcaAg+QSjddkNQu0ayoKKQU5DCRV3gCuItr1yzKShYlSWDl+1zvykHVhLlWsnBiua86DmXp++6PSPGUUzv//n5qVa34wp35gtuAulQwzEdmz3FIijXWd8psnOoVFI1nOp4M8YwcdggC7rK1rwbpG4QXcmKKSUNSk2v9fqaotPh3tRQ0Flz/0VWopO745stoVYvasm3KFT6F/Sa6qu+j9eCOZJ4q121IkzFuA3g6xJU9YiOEW145RKPFMdmL9mOw==

for:
- matrix:
    only:
    - job_name: macOS Mojave
  init:
  - system_profiler SPSoftwareDataType
  - cmake --version
  - gcc -v
  install:
  - chmod +x ${APPVEYOR_BUILD_FOLDER}/scripts/appveyor/install.sh
  - ${APPVEYOR_BUILD_FOLDER}/scripts/appveyor/install.sh
  before_build:
  - chmod +x ${APPVEYOR_BUILD_FOLDER}/scripts/appveyor/before_build.sh
  - ${APPVEYOR_BUILD_FOLDER}/scripts/appveyor/before_build.sh
  build_script:
  - cd build && make -j2
  - tests/sfizz_tests
  after_build:
  - chmod +x ${APPVEYOR_BUILD_FOLDER}/scripts/appveyor/after_build.sh
  - ${APPVEYOR_BUILD_FOLDER}/scripts/appveyor/after_build.sh
  test: off
  artifacts:
  - name: macOS Tarball
    path: "sfizz-*.tar.gz"

- matrix:
    only:
    - job_name: Windows x86
  cache: c:\tools\vcpkg\installed\ -> appveyor.yml
  install:      call %APPVEYOR_BUILD_FOLDER%\scripts\appveyor\install.cmd
  before_build: call %APPVEYOR_BUILD_FOLDER%\scripts\appveyor\before_build.cmd
  build_script: call %APPVEYOR_BUILD_FOLDER%\scripts\appveyor\build.cmd
  after_build:  call %APPVEYOR_BUILD_FOLDER%\scripts\appveyor\after_build.cmd
  artifacts:
  - name: x86 Setup
    path: "sfizz-*.exe"

- matrix:
    only:
    - job_name: Windows x64
  cache: c:\tools\vcpkg\installed\ -> appveyor.yml
  install:      call %APPVEYOR_BUILD_FOLDER%\scripts\appveyor\install.cmd
  before_build: call %APPVEYOR_BUILD_FOLDER%\scripts\appveyor\before_build.cmd
  build_script: call %APPVEYOR_BUILD_FOLDER%\scripts\appveyor\build.cmd
  after_build:  call %APPVEYOR_BUILD_FOLDER%\scripts\appveyor\after_build.cmd
  artifacts:
  - name: x64 Setup
    path: "sfizz-*.exe"

deploy:
- provider: GitHub
  auth_token:
    secure: xOugGAynvnZdc0DXaL3rlgMf4CICFLkdO8JxoRfLQMKJhkj/kZ4d8h7NCFneDzXG
  artifact: macOS Tarball,x86 Setup,x64 Setup
  draft: false
  prerelease: false
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
