language: cpp
os: linux
dist: bionic

jobs:
  include:
  - name: "macOS"
    os: osx
    env:
    - INSTALL_DIR="sfizz-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}"
    install: .travis/install_osx.sh
    script: .travis/script_osx.sh
    after_success: .travis/prepare_osx.sh
